FLASK_APP=sos_trades_api/server/base_server.py
FLASK_ENV=development
SOS_TRADES_SERVER_CONFIGURATION=C:\SoSTrades\Code\sostrades-webapi\sos_trades_api\configuration_template\configuration.json
SQL_ACCOUNT=root
SQL_PASSWORD=sushil123
LOG_USER=root
LOG_PASSWORD=sushil123
SECRET_KEY=ABCDEFGH12
