"""add pod flavors

Revision ID: 18d8890a5e5f
Revises: dda4d408a5e0
Create Date: 2024-03-22 10:20:46.055342

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '18d8890a5e5f'
down_revision = 'dda4d408a5e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference_study', sa.Column('generation_pod_flavor', sa.String(length=64), nullable=True))
    op.add_column('study_case', sa.Column('study_pod_flavor', sa.String(length=64), nullable=True))
    op.add_column('study_case', sa.Column('execution_pod_flavor', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_case', 'execution_pod_flavor')
    op.drop_column('study_case', 'study_pod_flavor')
    op.drop_column('reference_study', 'generation_pod_flavor')
    # ### end Alembic commands ###
