"""add error management on study object

Revision ID: 35ba4ee9fc53
Revises: f60bb248ada1
Create Date: 2021-12-01 15:35:13.637919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ba4ee9fc53'
down_revision = 'f60bb248ada1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_case', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('study_case', sa.Column('disabled', sa.Boolean(), nullable=False)),
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_case', 'error')
    op.drop_column('study_case', 'disabled')
    # ### end Alembic commands ###
