"""add keycloak_group in group

Revision ID: 45d4e338d0d8
Revises: 6d471f14fb35
Create Date: 2024-11-07 14:48:14.656946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45d4e338d0d8'
down_revision = '6d471f14fb35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_keycloak_group', sa.Boolean(), server_default=sa.text('false'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_column('is_keycloak_group')

    # ### end Alembic commands ###
