"""add stand alone status

Revision ID: 4800f7e11ae2
Revises: 6d471f14fb35
Create Date: 2025-05-22 11:07:27.645919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4800f7e11ae2'
down_revision = '6d471f14fb35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_stand_alone', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_case', schema=None) as batch_op:
        batch_op.drop_column('is_stand_alone')


    # ### end Alembic commands ###
