"""update pod allocation

Revision ID: 5b6303f4ab8e
Revises: 5acd0bb7bad9
Create Date: 2024-03-15 16:53:44.531536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b6303f4ab8e'
down_revision = '5acd0bb7bad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pod_allocation',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('identifier', sa.Integer(), nullable=False),
        sa.Column('kubernetes_pod_name', sa.String(length=128), nullable=True),
        sa.Column('kubernetes_pod_namespace', sa.String(length=128), nullable=True),
        sa.Column('pod_status', sa.String(length=64), server_default='', nullable=True),
        sa.Column('pod_type', sa.String(length=64), nullable=False),
        sa.Column('cpu_requested', sa.Integer(), nullable=True),
        sa.Column('memory_requested', sa.Integer(), nullable=True),
        sa.Column('cpu_limit', sa.Integer(), nullable=True),
        sa.Column('memory_limit', sa.Integer(), nullable=True),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.func.current_timestamp(), nullable=True),
        sa.Column('cpu_usage', sa.String(length=32), server_default='----', nullable=True),
        sa.Column('memory_usage', sa.String(length=32), server_default='----', nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    if op.execute('PRAGMA index_info("kubernetes_pod_name")') is not None:
        op.drop_index('kubernetes_pod_name', table_name='study_case_allocation')
    op.drop_table('study_case_allocation')
    op.drop_column('reference_study', 'kubernete_pod_name')
    op.drop_column('study_case_execution', 'kubernetes_pod_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.create_table('study_case_allocation',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('study_case_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=64), server_default=sa.text("''"), nullable=True),
    sa.Column('kubernetes_pod_name', mysql.VARCHAR(length=128), server_default=sa.text("''"), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('creation_date', mysql.DATETIME(), server_default=sa.func.current_timestamp(), nullable=True),
    sa.ForeignKeyConstraint(['study_case_id'], ['study_case.id'], name='fk_study_case_allocation_study_case_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('kubernetes_pod_name', 'study_case_allocation', ['kubernetes_pod_name'], unique=False)
    op.create_index('ix_study_case_allocation_study_case_id', 'study_case_allocation', ['study_case_id'], unique=False)
    op.add_column('study_case_execution', sa.Column('kubernetes_pod_name', mysql.VARCHAR(length=128), server_default=sa.text("''"), nullable=True))
    op.add_column('reference_study', sa.Column('kubernete_pod_name', mysql.VARCHAR(length=128), server_default=sa.text("''"), nullable=True))
    op.drop_table('pod_allocation')
    # ### end Alembic commands ###
