"""update user preference

Revision ID: 6742a7abbc12
Revises: 7df43d135e7c
Create Date: 2024-07-19 16:01:34.058228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6742a7abbc12'
down_revision = '7df43d135e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_study_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('panel_identifier', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('panel_opened', sa.Boolean(), nullable=True))
        batch_op.drop_column('preference')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_study_preference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preference', mysql.TEXT(), nullable=True))
        batch_op.drop_column('panel_opened')
        batch_op.drop_column('panel_identifier')

    # ### end Alembic commands ###
