"""update column execution message

Revision ID: 6d471f14fb35
Revises: 9187d11fbebc
Create Date: 2024-10-21 09:01:41.850232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d471f14fb35'
down_revision = '9187d11fbebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_case_execution', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=mysql.TEXT,
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_case_execution', schema=None) as batch_op:
        batch_op.alter_column('message',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###
