"""Add table favorite study

Revision ID: aede0731db6b
Revises: 0f797979d08f
Create Date: 2022-02-28 10:40:41.290528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aede0731db6b'
down_revision = '0f797979d08f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_study_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('study_case_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['study_case_id'], ['study_case.id'], name='fk_user_study_favorite_study_case_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_user_study_favorite_user_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_study_favorite')
    # ### end Alembic commands ###
