"""Add study case allocation table

Revision ID: cbf661e68ff3
Revises: d341b6f43c5b
Create Date: 2022-08-12 10:34:00.497218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf661e68ff3'
down_revision = 'd341b6f43c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_case_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_case_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), server_default='', nullable=True),
    sa.Column('kubernetes_pod_name', sa.String(length=128), server_default='', nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.func.current_timestamp(), nullable=True),
    sa.ForeignKeyConstraint(['study_case_id'], ['study_case.id'], name='fk_study_case_allocation_study_case_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kubernetes_pod_name')
    )
    op.create_index(op.f('ix_study_case_allocation_study_case_id'), 'study_case_allocation', ['study_case_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_case_allocation_study_case_id'), table_name='study_case_allocation')
    op.drop_table('study_case_allocation')
    # ### end Alembic commands ###
