"""Add device model to manage api-key by group

Revision ID: ead421cc5deb
Revises: 23659f27ce8a
Create Date: 2022-05-18 16:34:06.326494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead421cc5deb'
down_revision = '23659f27ce8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=80), nullable=True),
    sa.Column('device_key', sa.String(length=80), server_default='8536f2e37df1459493258c513477adc2', nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='fk_device_group_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device')
    # ### end Alembic commands ###
