'''
Copyright 2022 Airbus SAS
Modifications on 2024/06/07 Copyright 2024 Capgemini
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

'''
from alembic import op
from sqlalchemy.dialects import mysql

"""increase size of reference path

Revision ID: fb0a1fde7fe0
Revises: bcc99700bfe4
Create Date: 2022-09-21 11:28:43.480706

"""
# revision identifiers, used by Alembic.
revision = "fb0a1fde7fe0"
down_revision = "bcc99700bfe4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reference_study") as batch_op:
        batch_op.alter_column("reference_path",
                            existing_type=mysql.VARCHAR(length=128),
                            type_=mysql.VARCHAR(length=256),
                            existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("reference_study", "reference_path",
               existing_type=mysql.VARCHAR(length=256),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    # ### end Alembic commands ###
